#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
import argparse as ap
import logging
import pickle
import cv2

if __name__ == '__main__':
    parser = ap.ArgumentParser()
    parser.add_argument("ifile", default = "None")
    parser.add_argument("--svm", default = "None")
    parser.add_argument("--ofile", default = "None")

    args = parser.parse_args()

    

    
